name: photo_gallery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  # qr_flutter: ^4.0.0 <- Was added to Share Image by QR Code (Not Implemented)
  equatable: ^2.0.5
  # local_auth: ^2.1.6 <- Was added to Authenticate with Biometrics (Not Implemented)
  # mobile_scanner: ^3.1.1 <- Was added to Scan QR Code (Not Implemented)
  # image_picker: ^0.8.7
  camera: ^0.10.3+2
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
